import type { Metadata } from "next";
import {epilogue} from "./assets/fonts"
import "./globals.css";
import { Footer, Header } from "./components/SharedComponents";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={epilogue.className}>
        <Header />
        {children}
       
      </body>
    </html>
  );
}
